-- =====================================================================
-- Hospital FHIR Ops Lab — Oracle 19c 분기 참고 DDL
-- =====================================================================
-- 이 파일은 MySQL 8.x 정본 스키마(app/src/main/resources/db/migration/V1~V16)를
-- Oracle SQL 방언으로 번역한 참고 DDL이다. Flyway 마이그레이션으로 앱에 실제
-- 연결되어 있지는 않다(이 프로젝트의 DB는 MySQL 8.x 단일 구현이 정본이며, 이
-- 문서는 deliverable.md §2가 예고한 "별도 분기 문서"다).
--
-- 각 섹션은 대응하는 MySQL 마이그레이션 파일 번호(Vn)를 그대로 따서 표시했다 —
-- 다시 확인할 때 원본과 1:1로 대조하기 쉽게 하기 위함이다. Oracle에서 자연스러운
-- 형태로 재구성하지 않고, "MySQL DDL을 Oracle 방언으로 옮기면 무엇이 달라지는가"를
-- 그대로 드러내는 것을 우선했다(예: V3의 STORED 생성 컬럼 → Oracle은 VIRTUAL만
-- 지원, V5의 RENAME INDEX 문법 차이 등). 상세 문법 차이표는 같은 디렉터리의
-- mysql-oracle-dialect-diff.md 참고.
--
-- 실기동 검증: gvenzl/oracle-free:23-slim(커뮤니티 무료 이미지, Oracle Database
-- Free 23ai 기반) 컨테이너에 이 파일 전체를 sqlplus로 실제 적용해 전 구문이
-- 에러 없이 실행됨을 확인했다(2026-07-20). 상세는 README.md "실기동 결과" 참고 —
-- 라이선스가 필요한 진짜 Oracle 19c 이미지(container-registry.oracle.com, OTN
-- 계정 인증 필요)는 이 자동화 환경에서 받을 수 없어 미검증이며, 23ai와 19c는
-- 같은 SQL/PLSQL 방언 계열이라 문법 차이가 극히 적지만 100% 동일은 아니다.
-- =====================================================================


-- =====================================================================
-- V1: 레거시 HIS 핵심 스키마 (PATIENT / VISIT / LAB_RESULT / PRESCRIPTION)
-- =====================================================================
-- MySQL BIGINT AUTO_INCREMENT -> Oracle NUMBER(19) GENERATED BY DEFAULT AS
-- IDENTITY (12c+ 네이티브 identity column, 19c에서 지원). MySQL DATETIME ->
-- Oracle TIMESTAMP. ENGINE/CHARSET/COLLATE 절은 Oracle에 대응 개념이 없어
-- 제거(문자셋은 데이터베이스 생성 시 AL32UTF8로 지정하는 것으로 대체).
--
-- MySQL의 "DATETIME ... ON UPDATE CURRENT_TIMESTAMP"는 Oracle에 직접 대응
-- 문법이 없다 — Oracle은 컬럼 자동 갱신을 트리거로 구현해야 한다. 4개 테이블
-- 전부 같은 패턴이므로 PATIENT 하나에만 대표로 트리거를 달고 나머지 3개는
-- 동일 패턴이라는 점만 주석으로 남긴다(실제 분기 착수 시 4개 모두 동일하게
-- 복제하면 된다).

CREATE TABLE PATIENT (
    patient_id             NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_patient_uuid    VARCHAR2(64)  NOT NULL,
    birth_date              DATE          NULL,
    death_date              DATE          NULL,
    prefix                  VARCHAR2(20)  NULL,
    first_name              VARCHAR2(100) NULL,
    middle_name             VARCHAR2(100) NULL,
    last_name               VARCHAR2(100) NULL,
    suffix                  VARCHAR2(20)  NULL,
    maiden_name             VARCHAR2(100) NULL,
    marital_status          VARCHAR2(10)  NULL,
    race                    VARCHAR2(50)  NULL,
    ethnicity               VARCHAR2(50)  NULL,
    gender                  VARCHAR2(10)  NULL,
    birthplace              VARCHAR2(255) NULL,
    address                 VARCHAR2(255) NULL,
    city                    VARCHAR2(100) NULL,
    state                   VARCHAR2(100) NULL,
    county                  VARCHAR2(100) NULL,
    zip                     VARCHAR2(20)  NULL,
    created_at              TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at              TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_patient_source_uuid UNIQUE (source_patient_uuid)
);

-- MySQL "ON UPDATE CURRENT_TIMESTAMP" 대체 트리거 (PATIENT 대표 예시).
CREATE OR REPLACE TRIGGER trg_patient_updated_at
    BEFORE UPDATE ON PATIENT
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE TABLE VISIT (
    visit_id                NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id               NUMBER(19)    NOT NULL,
    source_encounter_uuid    VARCHAR2(64)  NOT NULL,
    started_at                TIMESTAMP     NULL,
    stopped_at                TIMESTAMP     NULL,
    encounter_class           VARCHAR2(50)  NULL,
    encounter_code            VARCHAR2(50)  NULL,
    encounter_description     VARCHAR2(500) NULL,
    reason_code                VARCHAR2(50)  NULL,
    reason_description         VARCHAR2(500) NULL,
    created_at                 TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at                 TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_visit_source_uuid UNIQUE (source_encounter_uuid),
    CONSTRAINT fk_visit_patient FOREIGN KEY (patient_id) REFERENCES PATIENT (patient_id)
);
-- 폭은 V4(아래) 기준으로 이미 반영(encounter_description/reason_description=500).

CREATE OR REPLACE TRIGGER trg_visit_updated_at
    BEFORE UPDATE ON VISIT
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE TABLE LAB_RESULT (
    lab_result_id           NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id                 NUMBER(19)    NOT NULL,
    patient_id                NUMBER(19)    NOT NULL,
    observed_at                TIMESTAMP     NULL,
    category                   VARCHAR2(50)  NULL,
    code                        VARCHAR2(50)  NOT NULL,
    description                 VARCHAR2(500) NULL,
    result_value                 VARCHAR2(255) NULL,
    units                         VARCHAR2(50)  NULL,
    value_type                    VARCHAR2(20)  NULL,
    created_at                    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at                    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_lab_result_visit FOREIGN KEY (visit_id) REFERENCES VISIT (visit_id),
    CONSTRAINT fk_lab_result_patient FOREIGN KEY (patient_id) REFERENCES PATIENT (patient_id)
);
-- uq_lab_result_natural 은 V3에서 result_value_key(생성 컬럼) 도입 후 걸린다(아래 참고).
-- MySQL은 처음에 (visit_id, code, observed_at)으로 걸었다가 V3에서 넓히지만,
-- Oracle 분기는 새 스키마이므로 처음부터 V3 반영 최종 형태로 한 번에 정의한다.

CREATE OR REPLACE TRIGGER trg_lab_result_updated_at
    BEFORE UPDATE ON LAB_RESULT
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE TABLE PRESCRIPTION (
    prescription_id          NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id                  NUMBER(19)    NOT NULL,
    patient_id                 NUMBER(19)    NOT NULL,
    medication_code              VARCHAR2(50)  NOT NULL,
    medication_description        VARCHAR2(600) NULL,
    started_at                     TIMESTAMP     NULL,
    stopped_at                      TIMESTAMP     NULL,
    reason_code                      VARCHAR2(50)  NULL,
    reason_description                VARCHAR2(500) NULL,
    created_at                         TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at                          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_prescription_visit FOREIGN KEY (visit_id) REFERENCES VISIT (visit_id),
    CONSTRAINT fk_prescription_patient FOREIGN KEY (patient_id) REFERENCES PATIENT (patient_id)
);
-- medication_description=600, reason_description=500 은 V4 폭 확장을 이미 반영.

CREATE OR REPLACE TRIGGER trg_prescription_updated_at
    BEFORE UPDATE ON PRESCRIPTION
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/


-- =====================================================================
-- V2: 표시용 식별자(synthetic_patient_no) 분리
-- =====================================================================
ALTER TABLE PATIENT ADD synthetic_patient_no VARCHAR2(32) NULL;

CREATE TABLE PATIENT_DISPLAY_ID (
    display_id_seq          NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id                NUMBER(19)   NOT NULL,
    synthetic_patient_no       VARCHAR2(32) NOT NULL,
    issued_at                    TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    is_active                     NUMBER(1)    DEFAULT 1 NOT NULL,
    CONSTRAINT uq_patient_display_id_no UNIQUE (synthetic_patient_no),
    CONSTRAINT fk_patient_display_id_patient FOREIGN KEY (patient_id) REFERENCES PATIENT (patient_id),
    CONSTRAINT chk_patient_display_id_active CHECK (is_active IN (0, 1))
);
-- MySQL BOOLEAN/TINYINT(1) -> Oracle 19c는 네이티브 BOOLEAN 컬럼이 없어(23c부터 지원)
-- NUMBER(1) + CHECK 제약으로 대체하는 것이 19c 호환 표준 패턴이다.

-- MySQL 원본은 "행이 없는 시점"을 이용해 즉시 NOT NULL+UNIQUE로 MODIFY했지만,
-- Oracle 분기는 새 스키마이므로 처음부터 NOT NULL로 정의하고 UNIQUE만 추가한다.
ALTER TABLE PATIENT MODIFY synthetic_patient_no VARCHAR2(32) NOT NULL;
ALTER TABLE PATIENT ADD CONSTRAINT uq_patient_synthetic_no UNIQUE (synthetic_patient_no);


-- =====================================================================
-- V3: LAB_RESULT/PRESCRIPTION 자연키 보강 (생성 컬럼 + 유니크)
-- =====================================================================
-- MySQL은 STORED 생성 컬럼(디스크에 실제 저장)을 쓰지만, Oracle 19c는 STORED를
-- 지원하지 않고 VIRTUAL(조회 시 계산, 인덱스는 가능)만 지원한다. 유니크
-- 제약/인덱스는 VIRTUAL 컬럼에도 그대로 걸 수 있어 기능적 동등성은 유지된다
-- (디스크 저장 여부만 다르고, "NULL끼리는 유니크 충돌 안 남" 문제를 고정
-- 센티널로 우회하는 목적은 동일하게 달성).
ALTER TABLE LAB_RESULT
    ADD result_value_key VARCHAR2(255)
        GENERATED ALWAYS AS (COALESCE(result_value, '')) VIRTUAL NOT NULL;

ALTER TABLE LAB_RESULT
    ADD CONSTRAINT uq_lab_result_natural UNIQUE (visit_id, code, observed_at, result_value_key);

ALTER TABLE PRESCRIPTION
    ADD stopped_at_key TIMESTAMP
        GENERATED ALWAYS AS (COALESCE(stopped_at, TIMESTAMP '9999-12-31 23:59:59')) VIRTUAL NOT NULL;

ALTER TABLE PRESCRIPTION
    ADD CONSTRAINT uq_prescription_natural UNIQUE (visit_id, medication_code, started_at, stopped_at_key);

-- 참고: MySQL 원본은 "새 인덱스 추가 -> 기존 인덱스 DROP -> RENAME INDEX" 3단계였다
-- (FK가 항상 인덱스를 갖고 있어야 하므로). Oracle 분기는 처음부터 최종 제약만
-- 한 번에 걸므로 이 절차가 필요 없다. 만약 기존 Oracle 스키마에 이미 구버전
-- 제약이 있고 이후 이 형태로 바꿔야 한다면 Oracle 문법은 다음과 같이 다르다:
--   ALTER INDEX uq_lab_result_natural_old RENAME TO uq_lab_result_natural;  (MySQL RENAME INDEX 대응)
--   DROP INDEX uq_lab_result_natural_old;                                   (MySQL DROP INDEX table.idx 대응 — Oracle은 스키마 레벨 오브젝트라 테이블명 없이 인덱스명만 씀)


-- =====================================================================
-- V4: 자유 텍스트 설명 컬럼 폭 확장
-- =====================================================================
-- Oracle 분기는 V1에서 이미 최종 폭(500/600)으로 정의했으므로 이 섹션은 변경
-- 사항 없음(신규 스키마라 중간 이력을 재현할 필요가 없기 때문). MySQL처럼
-- 기존 운영 스키마에 사후 반영해야 한다면 Oracle 문법은:
--   ALTER TABLE PRESCRIPTION MODIFY medication_description VARCHAR2(600);
--   ALTER TABLE PRESCRIPTION MODIFY reason_description VARCHAR2(500);
--   ALTER TABLE VISIT MODIFY encounter_description VARCHAR2(500);
--   ALTER TABLE VISIT MODIFY reason_description VARCHAR2(500);
--   ALTER TABLE LAB_RESULT MODIFY description VARCHAR2(500);
-- (MySQL은 컬럼명 앞에 MODIFY COLUMN, Oracle은 MODIFY만 쓰고 컬럼 타입을
-- 다시 명시하는 점은 동일하다 — 큰 차이는 아니지만 "COLUMN" 키워드 유무가 다르다.)


-- =====================================================================
-- V5: Spring Batch 메타데이터 + FHIR 동기화 캐시/워터마크
-- =====================================================================
-- 중요: BATCH_JOB_INSTANCE 등 8개 Spring Batch 메타데이터 테이블은 손으로
-- 번역하지 않는다. spring-batch-core-5.2.6.jar 안에
--   org/springframework/batch/core/schema-oracle.sql
-- 이 Oracle 전용 공식 스키마로 이미 포함되어 있다(BATCH_STEP_EXECUTION_SEQ 등
-- MySQL의 "유니크 제약을 건 1행짜리 카운터 테이블" 패턴 대신 Oracle 네이티브
-- SEQUENCE 오브젝트를 쓰는 등 구조 자체가 다르다). 이 파일을 직접 짜면
-- JobRepository 내부 SQL과 컬럼/제약이 미묘하게 어긋나 배치가 깨질 위험이
-- 있으므로, Oracle 분기 착수 시 반드시 그 jar 안의 원본 파일을 그대로
-- 사용한다(V5 원본 MySQL 마이그레이션 주석도 "임의로 손으로 짜지 않고 실제
-- 배포되는 스키마 원본을 사용"이라고 명시한 원칙과 동일한 이유).
--
-- 아래는 이 프로젝트가 직접 설계한 나머지 두 테이블(SYNC_WATERMARK,
-- FHIR_RESOURCE_CACHE)만 번역한다.

CREATE TABLE SYNC_WATERMARK (
    resource_type          VARCHAR2(30) PRIMARY KEY,
    last_synced_at           TIMESTAMP    DEFAULT TIMESTAMP '1970-01-01 00:00:00' NOT NULL,
    updated_at                 TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE OR REPLACE TRIGGER trg_sync_watermark_updated_at
    BEFORE UPDATE ON SYNC_WATERMARK
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- MySQL LONGTEXT -> Oracle CLOB.
CREATE TABLE FHIR_RESOURCE_CACHE (
    id                  NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_type         VARCHAR2(30) NOT NULL,
    source_table_pk         NUMBER(19)   NOT NULL,
    fhir_id                   VARCHAR2(64) NOT NULL,
    patient_fhir_id             VARCHAR2(64) NULL,  -- V7 반영(원본은 별도 ALTER)
    resource_json                 CLOB         NOT NULL,
    synced_at                       TIMESTAMP    NOT NULL,
    CONSTRAINT uq_fhir_cache_type_pk UNIQUE (resource_type, source_table_pk),
    CONSTRAINT uq_fhir_cache_type_fhir_id UNIQUE (resource_type, fhir_id)
);


-- =====================================================================
-- V6: 로컬 코드셋 테이블(CODE_SET) + 시드 데이터
-- =====================================================================
CREATE TABLE CODE_SET (
    id                   NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_system            VARCHAR2(30)  NOT NULL,
    source_code               VARCHAR2(50)  NOT NULL,
    source_description          VARCHAR2(500) NULL,
    fhir_system                    VARCHAR2(255) NOT NULL,
    fhir_code                        VARCHAR2(50)  NOT NULL,
    fhir_display                        VARCHAR2(500) NULL,
    CONSTRAINT uq_code_set_system_source UNIQUE (code_system, source_code)
);

-- MySQL은 "INSERT INTO ... VALUES (...), (...), (...)" 다중 행 문법을 지원하지만
-- Oracle은 단일 INSERT 문에 여러 VALUES 절을 못 쓴다(다중 행은 각각 별도 INSERT
-- 문이거나 "INSERT ALL ... SELECT * FROM DUAL"로 묶어야 한다). 여기서는 각 행을
-- 개별 INSERT 문으로 번역했다 — 원본 MySQL 시드 데이터(2026-07-18 실측, LAB_RESULT
-- 상위 다수 + PRESCRIPTION 상위 다수)와 값은 동일하다.
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '8462-4',  'Diastolic Blood Pressure', 'http://loinc.org', '8462-4',  'Diastolic Blood Pressure');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '8480-6',  'Systolic Blood Pressure', 'http://loinc.org', '8480-6',  'Systolic Blood Pressure');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '72514-3', 'Pain severity - 0-10 verbal numeric rating [Score] - Reported', 'http://loinc.org', '72514-3', 'Pain severity - 0-10 verbal numeric rating [Score] - Reported');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '8302-2',  'Body Height', 'http://loinc.org', '8302-2',  'Body Height');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '29463-7', 'Body Weight', 'http://loinc.org', '29463-7', 'Body Weight');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '8867-4',  'Heart rate', 'http://loinc.org', '8867-4',  'Heart rate');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '9279-1',  'Respiratory rate', 'http://loinc.org', '9279-1',  'Respiratory rate');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '72166-2', 'Tobacco smoking status', 'http://loinc.org', '72166-2', 'Tobacco smoking status');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '39156-5', 'Body mass index (BMI) [Ratio]', 'http://loinc.org', '39156-5', 'Body mass index (BMI) [Ratio]');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '76437-3', 'Primary insurance', 'http://loinc.org', '76437-3', 'Primary insurance');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '67875-5', 'Employment status - current', 'http://loinc.org', '67875-5', 'Employment status - current');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '56051-6', 'Hispanic or Latino', 'http://loinc.org', '56051-6', 'Hispanic or Latino');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '82589-3', 'Highest level of education', 'http://loinc.org', '82589-3', 'Highest level of education');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '32624-9', 'Race', 'http://loinc.org', '32624-9', 'Race');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '56799-0', 'Address', 'http://loinc.org', '56799-0', 'Address');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '54899-0', 'Preferred language', 'http://loinc.org', '54899-0', 'Preferred language');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '71802-3', 'Housing status', 'http://loinc.org', '71802-3', 'Housing status');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '93038-8', 'Stress level', 'http://loinc.org', '93038-8', 'Stress level');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '2093-3',  'Cholesterol [Mass/volume] in Serum or Plasma', 'http://loinc.org', '2093-3',  'Cholesterol [Mass/volume] in Serum or Plasma');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '6690-2',  'Leukocytes [#/volume] in Blood by Automated count', 'http://loinc.org', '6690-2',  'Leukocytes [#/volume] in Blood by Automated count');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '2571-8',  'Triglyceride [Mass/volume] in Serum or Plasma', 'http://loinc.org', '2571-8',  'Triglyceride [Mass/volume] in Serum or Plasma');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '789-8',   'Erythrocytes [#/volume] in Blood by Automated count', 'http://loinc.org', '789-8',   'Erythrocytes [#/volume] in Blood by Automated count');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '18262-6', 'Cholesterol in LDL [Mass/volume] in Serum or Plasma by Direct assay', 'http://loinc.org', '18262-6', 'Cholesterol in LDL [Mass/volume] in Serum or Plasma by Direct assay');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '786-4',   'MCHC [Entitic Mass/volume] in Red Blood Cells by Automated count', 'http://loinc.org', '786-4', 'MCHC [Entitic Mass/volume] in Red Blood Cells by Automated count');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '788-0',   'Erythrocyte [DistWidth] in Blood by Automated count', 'http://loinc.org', '788-0',   'Erythrocyte [DistWidth] in Blood by Automated count');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '787-2',   'MCV [Entitic mean volume] in Red Blood Cells by Automated count', 'http://loinc.org', '787-2', 'MCV [Entitic mean volume] in Red Blood Cells by Automated count');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '777-3',   'Platelets [#/volume] in Blood by Automated count', 'http://loinc.org', '777-3',   'Platelets [#/volume] in Blood by Automated count');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('LAB_RESULT', '785-6',   'MCH [Entitic mass] by Automated count', 'http://loinc.org', '785-6',   'MCH [Entitic mass] by Automated count');

INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '310798', 'Hydrochlorothiazide 25 MG Oral Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '310798', 'Hydrochlorothiazide 25 MG Oral Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '308136', 'amLODIPine 2.5 MG Oral Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '308136', 'amLODIPine 2.5 MG Oral Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '895996', '120 ACTUAT fluticasone propionate 0.044 MG/ACTUAT Metered Dose Inhaler [Flovent]', 'http://www.nlm.nih.gov/research/umls/rxnorm', '895996', '120 ACTUAT fluticasone propionate 0.044 MG/ACTUAT Metered Dose Inhaler [Flovent]');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '630208', 'albuterol 0.83 MG/ML Inhalation Solution', 'http://www.nlm.nih.gov/research/umls/rxnorm', '630208', 'albuterol 0.83 MG/ML Inhalation Solution');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '314076', 'lisinopril 10 MG Oral Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '314076', 'lisinopril 10 MG Oral Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '313521', 'tropicamide 5 MG/ML Ophthalmic Solution', 'http://www.nlm.nih.gov/research/umls/rxnorm', '313521', 'tropicamide 5 MG/ML Ophthalmic Solution');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '313782', 'Acetaminophen 325 MG Oral Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '313782', 'Acetaminophen 325 MG Oral Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '310965', 'Ibuprofen 200 MG Oral Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '310965', 'Ibuprofen 200 MG Oral Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '313820', 'Acetaminophen 160 MG Chewable Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '313820', 'Acetaminophen 160 MG Chewable Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '562251', 'Amoxicillin 250 MG / Clavulanate 125 MG Oral Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '562251', 'Amoxicillin 250 MG / Clavulanate 125 MG Oral Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '849574', 'Naproxen sodium 220 MG Oral Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '849574', 'Naproxen sodium 220 MG Oral Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '198405', 'Ibuprofen 100 MG Oral Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '198405', 'Ibuprofen 100 MG Oral Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '206905', 'Ibuprofen 400 MG Oral Tablet [Ibu]', 'http://www.nlm.nih.gov/research/umls/rxnorm', '206905', 'Ibuprofen 400 MG Oral Tablet [Ibu]');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '834102', 'Penicillin V Potassium 500 MG Oral Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '834102', 'Penicillin V Potassium 500 MG Oral Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '1049630','diphenhydrAMINE Hydrochloride 25 MG Oral Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '1049630','diphenhydrAMINE Hydrochloride 25 MG Oral Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '309097', 'Cefuroxime 250 MG Oral Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '309097', 'Cefuroxime 250 MG Oral Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '834061', 'Penicillin V Potassium 250 MG Oral Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '834061', 'Penicillin V Potassium 250 MG Oral Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '308192', 'Amoxicillin 500 MG Oral Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '308192', 'Amoxicillin 500 MG Oral Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '197454', 'cephalexin 500 MG Oral Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '197454', 'cephalexin 500 MG Oral Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '308182', 'Amoxicillin 250 MG Oral Capsule', 'http://www.nlm.nih.gov/research/umls/rxnorm', '308182', 'Amoxicillin 250 MG Oral Capsule');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '197511', 'ciprofloxacin 250 MG Oral Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '197511', 'ciprofloxacin 250 MG Oral Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '860975', '24 HR Metformin hydrochloride 500 MG Extended Release Oral Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '860975', '24 HR Metformin hydrochloride 500 MG Extended Release Oral Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '310325', 'ferrous sulfate 325 MG Oral Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '310325', 'ferrous sulfate 325 MG Oral Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '309362', 'Clopidogrel 75 MG Oral Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '309362', 'Clopidogrel 75 MG Oral Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '312961', 'Simvastatin 20 MG Oral Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '312961', 'Simvastatin 20 MG Oral Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '866412', '24 HR metoprolol succinate 100 MG Extended Release Oral Tablet', 'http://www.nlm.nih.gov/research/umls/rxnorm', '866412', '24 HR metoprolol succinate 100 MG Extended Release Oral Tablet');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '705129', 'Nitroglycerin 0.4 MG/ACTUAT Mucosal Spray', 'http://www.nlm.nih.gov/research/umls/rxnorm', '705129', 'Nitroglycerin 0.4 MG/ACTUAT Mucosal Spray');
INSERT INTO CODE_SET (code_system, source_code, source_description, fhir_system, fhir_code, fhir_display) VALUES ('PRESCRIPTION', '311700', 'Midazolam 1 MG/ML Injectable Solution', 'http://www.nlm.nih.gov/research/umls/rxnorm', '311700', 'Midazolam 1 MG/ML Injectable Solution');


-- =====================================================================
-- V7: FHIR_RESOURCE_CACHE.patient_fhir_id + 인덱스
-- =====================================================================
-- Oracle 분기는 V5 CREATE TABLE에 이미 patient_fhir_id를 포함해 정의했으므로
-- ALTER TABLE ADD COLUMN은 생략한다(신규 스키마 특성상 V4와 동일한 이유).
-- 인덱스만 별도로 생성(Oracle CREATE INDEX 문법은 MySQL과 동일).
CREATE INDEX idx_fhir_cache_type_patient ON FHIR_RESOURCE_CACHE (resource_type, patient_fhir_id);


-- =====================================================================
-- V8: 인증 스키마 (APP_ROLE / APP_USER / APP_USER_ROLE)
-- =====================================================================
CREATE TABLE APP_ROLE (
    role_id      NUMBER(19)  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name      VARCHAR2(50) NOT NULL,
    CONSTRAINT uq_app_role_name UNIQUE (role_name)
);

CREATE TABLE APP_USER (
    user_id          NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username           VARCHAR2(50)  NOT NULL,
    password_hash        VARCHAR2(255) NOT NULL,
    enabled                 NUMBER(1)     DEFAULT 1 NOT NULL,
    created_at                TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_app_user_username UNIQUE (username),
    CONSTRAINT chk_app_user_enabled CHECK (enabled IN (0, 1))
);

CREATE TABLE APP_USER_ROLE (
    user_id NUMBER(19) NOT NULL,
    role_id NUMBER(19) NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_app_user_role_user FOREIGN KEY (user_id) REFERENCES APP_USER (user_id),
    CONSTRAINT fk_app_user_role_role FOREIGN KEY (role_id) REFERENCES APP_ROLE (role_id)
);

INSERT INTO APP_ROLE (role_name) VALUES ('ROLE_SYSTEM_ADMIN');


-- =====================================================================
-- V9: RBAC 5역할 완성 + ACCESS_POLICY_RULES
-- =====================================================================
CREATE TABLE ACCESS_POLICY_RULES (
    rule_id        NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name        VARCHAR2(50)  NOT NULL,
    url_pattern         VARCHAR2(200) NOT NULL,
    allowed                NUMBER(1)     DEFAULT 1 NOT NULL,
    description               VARCHAR2(255) NULL,
    CONSTRAINT fk_access_policy_role FOREIGN KEY (role_name) REFERENCES APP_ROLE (role_name),
    CONSTRAINT uq_access_policy_role_pattern UNIQUE (role_name, url_pattern),
    CONSTRAINT chk_access_policy_allowed CHECK (allowed IN (0, 1))
);

INSERT INTO APP_ROLE (role_name) VALUES ('ROLE_PHYSICIAN');
INSERT INTO APP_ROLE (role_name) VALUES ('ROLE_NURSE');
INSERT INTO APP_ROLE (role_name) VALUES ('ROLE_REGISTRAR');
INSERT INTO APP_ROLE (role_name) VALUES ('ROLE_AUDITOR');

INSERT INTO ACCESS_POLICY_RULES (role_name, url_pattern, allowed, description) VALUES ('ROLE_PHYSICIAN',    '/dashboard', 1, '대시보드 - 전 역할 공통 접근');
INSERT INTO ACCESS_POLICY_RULES (role_name, url_pattern, allowed, description) VALUES ('ROLE_NURSE',        '/dashboard', 1, '대시보드 - 전 역할 공통 접근');
INSERT INTO ACCESS_POLICY_RULES (role_name, url_pattern, allowed, description) VALUES ('ROLE_REGISTRAR',    '/dashboard', 1, '대시보드 - 전 역할 공통 접근');
INSERT INTO ACCESS_POLICY_RULES (role_name, url_pattern, allowed, description) VALUES ('ROLE_SYSTEM_ADMIN', '/dashboard', 1, '대시보드 - 전 역할 공통 접근');
INSERT INTO ACCESS_POLICY_RULES (role_name, url_pattern, allowed, description) VALUES ('ROLE_AUDITOR',      '/dashboard', 1, '대시보드 - 전 역할 공통 접근');
INSERT INTO ACCESS_POLICY_RULES (role_name, url_pattern, allowed, description) VALUES ('ROLE_SYSTEM_ADMIN', '/admin/system', 1, '시스템 관리 화면(placeholder) - 전산관리자 전용');
INSERT INTO ACCESS_POLICY_RULES (role_name, url_pattern, allowed, description) VALUES ('ROLE_AUDITOR',      '/audit/preview', 1, '감사 로그 화면(placeholder) - 감사자 전용, Phase 5.2에서 대체 예정');


-- =====================================================================
-- V10: AUDIT_LOG
-- =====================================================================
CREATE TABLE AUDIT_LOG (
    audit_id         NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_username      VARCHAR2(50)  NOT NULL,
    target_pk               VARCHAR2(100) NULL,
    action                     VARCHAR2(100) NOT NULL,
    purpose                       VARCHAR2(500) NULL,
    masked                          NUMBER(1)     DEFAULT 0 NOT NULL,
    ip_address                        VARCHAR2(45)  NULL,
    success                              NUMBER(1)     NOT NULL,
    result_code                            VARCHAR2(50)  NOT NULL,
    occurred_at                              TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_audit_log_masked CHECK (masked IN (0, 1)),
    CONSTRAINT chk_audit_log_success CHECK (success IN (0, 1))
);

CREATE INDEX idx_audit_log_actor_occurred ON AUDIT_LOG (actor_username, occurred_at);
CREATE INDEX idx_audit_log_result_code ON AUDIT_LOG (result_code);


-- =====================================================================
-- V11: 대량 복호 3단계 승인 상태머신
-- =====================================================================
CREATE TABLE BULK_DECRYPTION_REQUEST (
    request_id       NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requested_by        VARCHAR2(50)  NOT NULL,
    reason                  VARCHAR2(500) NOT NULL,
    status                      VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
    requested_at                    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    decided_by                          VARCHAR2(50)  NULL,
    decided_at                              TIMESTAMP     NULL,
    decision_note                              VARCHAR2(500) NULL,
    CONSTRAINT chk_bulk_decryption_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE INDEX idx_bulk_decryption_status ON BULK_DECRYPTION_REQUEST (status);
CREATE INDEX idx_bulk_decryption_requested_by ON BULK_DECRYPTION_REQUEST (requested_by);


-- =====================================================================
-- V12 / V14 / V16: ACCESS_POLICY_RULES 후속 등록 (통계/actuator/리포트)
-- =====================================================================
INSERT INTO ACCESS_POLICY_RULES (role_name, url_pattern, allowed, description) VALUES ('ROLE_AUDITOR',      '/stats/**', 1, '통계(k=5 익명성) API - 감사자/전산관리자 전용');
INSERT INTO ACCESS_POLICY_RULES (role_name, url_pattern, allowed, description) VALUES ('ROLE_SYSTEM_ADMIN', '/stats/**', 1, '통계(k=5 익명성) API - 감사자/전산관리자 전용');

INSERT INTO ACCESS_POLICY_RULES (role_name, url_pattern, allowed, description) VALUES ('ROLE_AUDITOR',      '/actuator/metrics',    1, 'Actuator 메트릭 목록 조회 - 감사자/전산관리자 전용');
INSERT INTO ACCESS_POLICY_RULES (role_name, url_pattern, allowed, description) VALUES ('ROLE_SYSTEM_ADMIN', '/actuator/metrics',    1, 'Actuator 메트릭 목록 조회 - 감사자/전산관리자 전용');
INSERT INTO ACCESS_POLICY_RULES (role_name, url_pattern, allowed, description) VALUES ('ROLE_AUDITOR',      '/actuator/metrics/**', 1, 'Actuator 메트릭 상세 조회 - 감사자/전산관리자 전용');
INSERT INTO ACCESS_POLICY_RULES (role_name, url_pattern, allowed, description) VALUES ('ROLE_SYSTEM_ADMIN', '/actuator/metrics/**', 1, 'Actuator 메트릭 상세 조회 - 감사자/전산관리자 전용');

INSERT INTO ACCESS_POLICY_RULES (role_name, url_pattern, allowed, description) VALUES ('ROLE_AUDITOR',      '/reports/patient-visit-summary', 1, '환자별 방문 요약 리포트 - 감사자/전산관리자 전용');
INSERT INTO ACCESS_POLICY_RULES (role_name, url_pattern, allowed, description) VALUES ('ROLE_SYSTEM_ADMIN', '/reports/patient-visit-summary', 1, '환자별 방문 요약 리포트 - 감사자/전산관리자 전용');


-- =====================================================================
-- V15: AUDIT_LOG.target_pk 인덱스
-- =====================================================================
CREATE INDEX idx_audit_log_target_pk ON AUDIT_LOG (target_pk);


-- =====================================================================
-- V13: PATIENT_VISIT_SUMMARY — Oracle 분기는 물리 테이블 대신 Materialized
-- View로 구현한다(§0 미확정 사항 재결정 결과 — 근거는 README.md 참고).
-- 정의는 query-optimization-mv.sql 참고.
-- =====================================================================

COMMIT;
