-- Phase 2 Step 2.1: Spring Batch 메타데이터 스키마 + FHIR 동기화 캐시/워터마크 테이블
--
-- 설계 판단 1: Spring Batch(5.2.6, spring-boot-starter-batch 전이 의존성)는 JobRepository가
-- JDBC 기반으로 동작하려면 BATCH_JOB_INSTANCE 등 자체 메타데이터 테이블이 필요하다. 이
-- 프로젝트는 스키마 소유권을 전부 Flyway로 일원화하는 원칙이라(V1~V4 전부 Flyway), Spring
-- Boot의 자동 배치 스키마 초기화(spring.batch.jdbc.initialize-schema)는 껴서(application.yml,
-- never로 설정) 이 마이그레이션이 그 스키마를 유일하게 소유하게 한다. 아래 CREATE TABLE
-- 블록은 spring-batch-core-5.2.6.jar 안의 org/springframework/batch/core/schema-mysql.sql을
-- 그대로 가져온 것이다(임의로 손으로 짜지 않고 실제 배포되는 스키마 원본을 사용 — 컬럼
-- 폭/제약을 잘못 짐작해 JobRepository 동작이 깨지는 것을 방지). ENGINE=InnoDB만 유지하고
-- 이 프로젝트의 문자셋 컨벤션(utf8mb4/utf8mb4_0900_ai_ci)을 추가했다.

CREATE TABLE BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT,
    JOB_NAME VARCHAR(100) NOT NULL,
    JOB_KEY VARCHAR(32) NOT NULL,
    CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    CREATE_TIME DATETIME(6) NOT NULL,
    START_TIME DATETIME(6) DEFAULT NULL,
    END_TIME DATETIME(6) DEFAULT NULL,
    STATUS VARCHAR(10),
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED DATETIME(6),
    CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID)
        REFERENCES BATCH_JOB_INSTANCE (JOB_INSTANCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID BIGINT NOT NULL,
    PARAMETER_NAME VARCHAR(100) NOT NULL,
    PARAMETER_TYPE VARCHAR(100) NOT NULL,
    PARAMETER_VALUE VARCHAR(2500),
    IDENTIFYING CHAR(1) NOT NULL,
    CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    CREATE_TIME DATETIME(6) NOT NULL,
    START_TIME DATETIME(6) DEFAULT NULL,
    END_TIME DATETIME(6) DEFAULT NULL,
    STATUS VARCHAR(10),
    COMMIT_COUNT BIGINT,
    READ_COUNT BIGINT,
    FILTER_COUNT BIGINT,
    WRITE_COUNT BIGINT,
    READ_SKIP_COUNT BIGINT,
    WRITE_SKIP_COUNT BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT BIGINT,
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED DATETIME(6),
    CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
        REFERENCES BATCH_STEP_EXECUTION (STEP_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE BATCH_STEP_EXECUTION_SEQ (
    ID BIGINT NOT NULL,
    UNIQUE_KEY CHAR(1) NOT NULL,
    CONSTRAINT BATCH_STEP_EXECUTION_SEQ_UN UNIQUE (UNIQUE_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO BATCH_STEP_EXECUTION_SEQ (ID, UNIQUE_KEY)
    SELECT * FROM (SELECT 0 AS ID, '0' AS UNIQUE_KEY) AS tmp
    WHERE NOT EXISTS (SELECT * FROM BATCH_STEP_EXECUTION_SEQ);

CREATE TABLE BATCH_JOB_EXECUTION_SEQ (
    ID BIGINT NOT NULL,
    UNIQUE_KEY CHAR(1) NOT NULL,
    CONSTRAINT BATCH_JOB_EXECUTION_SEQ_UN UNIQUE (UNIQUE_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO BATCH_JOB_EXECUTION_SEQ (ID, UNIQUE_KEY)
    SELECT * FROM (SELECT 0 AS ID, '0' AS UNIQUE_KEY) AS tmp
    WHERE NOT EXISTS (SELECT * FROM BATCH_JOB_EXECUTION_SEQ);

CREATE TABLE BATCH_JOB_SEQ (
    ID BIGINT NOT NULL,
    UNIQUE_KEY CHAR(1) NOT NULL,
    CONSTRAINT BATCH_JOB_SEQ_UN UNIQUE (UNIQUE_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO BATCH_JOB_SEQ (ID, UNIQUE_KEY)
    SELECT * FROM (SELECT 0 AS ID, '0' AS UNIQUE_KEY) AS tmp
    WHERE NOT EXISTS (SELECT * FROM BATCH_JOB_SEQ);

-- 설계 판단 2: 워터마크는 FHIR 리소스 타입(Patient/Encounter/Observation/MedicationRequest)을
-- 키로 삼는다 — 레거시 테이블명(PATIENT/VISIT/...)이 아니라 변환 대상 기준으로 잡아야
-- SyncJob의 스텝 이름·캐시 테이블의 resource_type과 한 어휘로 대응되어 추적하기 쉽다.
CREATE TABLE SYNC_WATERMARK (
    resource_type     VARCHAR(30) NOT NULL PRIMARY KEY,
    last_synced_at    DATETIME    NOT NULL DEFAULT '1970-01-01 00:00:00',
    updated_at        DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 설계 판단 3: source_table_pk는 변환 대상 레거시 테이블의 불변 내부 PK(patient_id/
-- visit_id/lab_result_id/prescription_id)를 그대로 담는다 — resource_type과 묶어야만
-- 유일해지므로(서로 다른 리소스 타입끼리는 PK 값 공간이 겹칠 수 있음) 복합 UNIQUE로
-- 멱등 upsert를 강제한다. fhir_id는 외부에 노출하는 FHIR 리소스 id이며 resource_type과
-- 묶어 조회 UNIQUE도 함께 둔다(Step 2.4 REST API가 이 조합으로 조회).
CREATE TABLE FHIR_RESOURCE_CACHE (
    id                BIGINT AUTO_INCREMENT PRIMARY KEY,
    resource_type     VARCHAR(30)  NOT NULL,
    source_table_pk   BIGINT       NOT NULL,
    fhir_id           VARCHAR(64)  NOT NULL,
    resource_json     LONGTEXT     NOT NULL,
    synced_at         DATETIME     NOT NULL,
    CONSTRAINT uq_fhir_cache_type_pk UNIQUE (resource_type, source_table_pk),
    CONSTRAINT uq_fhir_cache_type_fhir_id UNIQUE (resource_type, fhir_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
